#ifndef UART_CONFIG_H
#define UART_CONFIG_H

/*any value calculated using the equation desiered_baudrate=freq/(16*USARTDIV) )
baudrate=((mantisa of USARTDIV)|(exponent of USARTDIV * 16))*/
#define USART_BAUDRATE 				USART_BAUDRATE_9600
/*USART_CR1_MWORD_LENGTH_8BITS,USART_CR1_MWORD_LENGTH_9BITS*/
#define USART_WORD_LENGTH_CONFIG 	USART_CR1_MWORD_LENGTH_8BITS 
/*USART_CR1_PE_DISABLE,USART_CR1_PE_ENABLED*/
#define USART_PARITY_CONFIG 		USART_CR1_PE_DISABLE
/*USART_CR1_PS_EVEN,USART_CR1_PS_ODD*/
#define USART_PS_CONFIG				USART_CR1_PS_EVEN
/*USART_CR1_PEIE_DISABLE,USART_CR1_PEIE_ENABLED*/
#define USART_PEIE_CONFIG			USART_CR1_PEIE_DISBALE
/*USART_CR1_TXEIE_DISABLE,USART_CR1_TXEIE_ENABLED*/
#define USART_TXEIE_CONFIG			USART_CR1_TXEIE_ENABLE
/*USART_CR1_TCIE_DISABLE,USART_CR1_TCIE_ENABLED*/
#define USART_TCIE_CONFIG			USART_CR1_TCIE_DISABLE
/*USART_CR1_RXNEIE_DISABLE,USART_CR1_RXNEIE_ENABLED*/
#define USART_RXENE_CONFIG			USART_CR1_RXNEIE_ENABLE
/*USART_CR1_TE_DISABLE,USART_CR1_TE_ENABLED*/
#define USART_TE_CONFIG 			USART_CR1_TE_ENABLE
/*USART_CR1_RE_DISABLE,USART_CR1_RE_ENABLED*/
#define	USART_RE_CONFIG 			USART_CR1_RE_ENABLE
/*USART_CR2_STOPBITS_1,USART_CR2_STOPBITS_0_5,USART_CR2_STOPBITS_2,USART_CR2_STOPBITS_1_5*/
#define USART_STOPBITS_CONFIG		USART_CR2_STOPBITS_1
/*USART_CR3_HDSEL_HALF_DUPLEX_OFF,USART_CR3_HDSEL_HALF_DUPLEX_ON*/
#define USART_HALFDUPLEX_CONFIG		USART_CR3_HDSEL_HALF_DUPLEX_OFF

#endif
