#ifndef UART_CONFIG_H
#define UART_CONFIG_H

#define USART1_TX_PORT 				GPIO_PORT_A
#define USART1_TX_PIN  				GPIO_PIN9 
#define USART1_TX_MODE 				GPIO_CNF_GPO_PUSH_PULL
#define USART1_TX_SPEED 			GPIO_MODE_OUTPUT_50_MHZ

#define USART1_RX_PORT 				GPIO_PORT_A
#define USART1_RX_PIN  				GPIO_PIN10
#define USART1_RX_CNF				GPIO_CNF_IP_PULL_UP_DOWN
#define USART1_RX_MODE 				GPIO_MODE_INPUT

#define USART_BAUDRATE 				USART_BAUDRATE_9600_8MHZ

#define USART_WORD_LENGTH_CONFIG 	USART_CR1_MWORD_LENGTH_8BITS
#define USART_PARITY_CONFIG 		USART_CR1_PE_DISABLE
#define USART_PS_CONFIG				USART_CR1_PS_EVEN
#define USART_PEIE_CONFIG			USART_CR1_PEIE_DISBALE
#define USART_TXEIE_CONFIG			USART_CR1_TXEIE_ENABLE
#define USART_TCIE_CONFIG			USART_CR1_TCIE_DISABLE
#define USART_RXENE_CONFIG			USART_CR1_RXNEIE_ENABLE
#define USART_TE_CONFIG 			USART_CR1_TE_ENABLE
#define	USART_RE_CONFIG 			USART_CR1_RE_ENABLE

#define USART_STOPBITS				USART_CR2_STOPBITS_1
#define USART_HALFDUPLEX			USART_CR3_HDSEL_HALF_DUPLEX_OFF

#endif