#ifndef HLED_CONFIG_H
#define HLED_CONFIG_H 

#define HLED_LOW 0
#define HLED_HIGH 0x40000

#define LED_CONFIG(PIN,PORT,ACTIVE) (PIN | PORT | ACTIVE)

#define HLED_PORTA 0x10000
#define HLED_PORTB 0x20000
#define HLED_PORTC 0x30000

#define LED_0 LED_CONFIG(GPIO_PIN3,HLED_PORTA,HLED_HIGH)
#define LED_1 LED_CONFIG(GPIO_PIN7,HLED_PORTB,HLED_HIGH)
#define LED_2 LED_CONFIG(GPIO_PIN12,HLED_PORTA,HLED_HIGH)
#define LED_3 LED_CONFIG(GPIO_PIN4,HLED_PORTB,HLED_HIGH)
#define LED_4 LED_CONFIG(GPIO_PIN13,HLED_PORTC,HLED_LOW)

#define HLED_PIN_MASK 0xFFFF

#define HLED_PORTA_LEDS ((LED_0 | LED_2) & HLED_PIN_MASK)

#define HLED_PORTB_LEDS ((LED_1 | LED_3) & HLED_PIN_MASK)

#define HLED_PORTC_LEDS ((LED_4) & HLED_PIN_MASK)

#endif
